import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './globals.css';

export const metadata = {
  title: '충북대학교 SW중심대학사업단 Online Judge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/logo.png" />
      </head>
      <body className="text-sm">
        <Navbar />
        <div className="overflow-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
